name: nmrcryspy
channels:
  - anaconda
  - conda-forge
dependencies:
  - numpy>=1.20
  - setuptools>=27.3
  - matplotlib>=3.3.4
  - pandas>=1.1.3
  - pip
  - pip:
      - monty>=2.0.4
      - csdmpy>=0.4.1
      - pydantic>=1.9
      - typing-extensions>=3.7
      - psutil>=5.4.8
      - joblib>=1.0.0
      # building docs
      - sphinx>=2.0
      - sphinxjp.themes.basicstrap
      - sphinx-copybutton>=0.2.12
      - sphinx-gallery>=0.10
      - pillow>=7.1.2
      - breathe==4.26
      - sphinx-tabs>=1.1.13
      - recommonmark
      - sphinx-version-warning
